Repository cse112-sp22-group4/Electric-Pomato, pull requests merged in 2022-04, with the labels that each got.

#27 Update package.json repo urls
  package.json
Labels: cleanup

#29 Add backend functions
  source/js/TaskList.js
  source/js/backend.js
Labels: cleanup

#30 Changed localStorage calls to new functions (app.js, breakPrompt.js)
  source/js/BreakPrompt.js
  source/js/app.js
Labels: cleanup

#28 Js doc refactor
  source/js/EditableTaskList.js
  source/js/LogsButton.js
  source/js/StartButtons.js
  source/js/TomatoSlider.js
  source/js/ViewOnlyTaskList.js
  source/js/ViewOnlyTaskListSection.js
  source/js/done.js
Labels: documentation, cleanup

#34 update node-sass to sass
  package-lock.json
  package.json
Labels: cleanup

#32 Jest node options
  babel.config.cjs
  package-lock.json
  package.json
  source/__tests__/BreakPrompt.test.js
  source/__tests__/StartButtons.test.js
  source/__tests__/StartContainer.test.js
  source/__tests__/Timer.test.js
  source/__tests__/TimerUI.test.js
  source/__tests__/UsernameInput.test.js
  source/__tests__/ViewOnlyTaskList.test.js
  source/__tests__/WelcomeMessage.test.js
Labels: cleanup, testing

#24 Organize JS files into folders
  source/__tests__/BreakPrompt.test.js
  source/__tests__/CurrentYear.test.js
  source/__tests__/EditableTaskList.test.js
  source/__tests__/StartButtons.test.js
  source/__tests__/StartContainer.test.js
  source/__tests__/TaskList.test.js
  source/__tests__/Timer.test.js
  source/__tests__/TimerUI.test.js
  source/__tests__/UsernameInput.test.js
  source/__tests__/ViewOnlyTaskList.test.js
  source/__tests__/WelcomeMessage.test.js
  source/app.html
  source/done.html
  source/index.html
  source/js/classes/PopUp.js
  source/js/classes/TaskList.js
  source/js/classes/Timer.js
  source/js/components/BreakPrompt.js
  source/js/components/CurrentYear.js
  source/js/components/EditableTaskList.js
  source/js/components/EditableTaskListBody.js
  source/js/components/EditableTaskListInput.js
  source/js/components/LogsButton.js
  source/js/components/StartButtons.js
  source/js/components/StartContainer.js
  source/js/components/TimerUI.js
  source/js/components/TomatoSlider.js
  source/js/components/UsernameInput.js
  source/js/components/ViewOnlyTaskList.js
  source/js/components/ViewOnlyTaskListSection.js
  source/js/components/WelcomeMessage.js
  source/js/constants/lineColors.js
  source/js/constants/lineConfig.js
  source/js/scripts/app.js
  source/js/scripts/done.js
Labels: cleanup
