Repository cse112-sp22-group4/Electric-Pomato, pull requests merged in 2022-06, with the labels that each got.

#157 Enhancement/UI themes
  cypress/integration/TaskTime.js
  mocks/fileMock.js
  package.json
  source/__tests__/TimerUI.test.js
  source/app.html
  source/img/bombBreak.svg
  source/img/bombPomo.svg
  source/img/bombWhite.svg
  source/img/green.svg
  source/img/red.svg
  source/img/tomGreen.svg
  source/img/tomRed.svg
  source/img/tomWhite.svg
  source/index.html
  source/js/components/IntroIcons.js
  source/js/components/SettingsModal.js
  source/js/components/TimerUI.js
  source/js/components/TomatoSlider.js
  source/js/constants/themeIcons.js
  source/js/scripts/app.js
  source/scss/app.scss
  source/scss/components.scss
  svgo.config.json
Labels: enhancement

#172 Keyboard accessibility on pomos
  source/__tests__/EditableTaskList.test.js
  source/js/components/EditableTaskListBody.js
  source/js/components/TomatoSlider.js
Labels: enhancement

#191 meeting notes from today
  README.md
  admin/meetings/Final Meeting.pdf
Labels: documentation

#146 Update instruction cards to have images
  cypress/support/index.js
  source/img/create-task-list-mobile.png
  source/img/create-task-list.png
  source/img/settings-modal.png
  source/img/stats-modal-mobile.png
  source/img/stats-modal.png
  source/img/viewable-task-list-mobile.png
  source/img/viewable-task-list.png
  source/js/components/InfoModal.js
  source/scss/components.scss
Labels: enhancement

#193 Fix issue with service worker not registering
  cypress/support/index.js
  source/index.html
Labels: bug

#195 Cleanup parcel config files
  .htmlnanorc
  .parcelrc
  package.json
Labels: cleanup

#167 Implement remaining pomos indicator
  source/__tests__/EditableTaskList.test.js
  source/__tests__/RemainingPomos.test.js
  source/__tests__/ViewOnlyTaskList.test.js
  source/app.html
  source/js/components/InfoModal.js
  source/js/components/RemainingPomos.js
  source/js/components/StatsModal.js
  source/js/scripts/app.js
  source/scss/app.scss
  source/scss/components.scss
Labels: enhancement

#179 cleanup styling to be more responsive on mobile
  source/app.html
  source/index.html
  source/js/components/MenuIcons.js
  source/js/components/StatsModal.js
  source/scss/app.scss
  source/scss/components.scss
  source/scss/index.scss
  source/scss/themes.scss
Labels: enhancement, UI

#196 fix settings bug
  source/js/components/SettingsModal.js
Labels: bug

#189 Add titles to buttons on home page
  package-lock.json
  source/index.html
  source/js/components/WelcomeMessage.js
Labels: enhancement, UI

#194 Audio notifications toggle in settings
  source/js/backend.js
  source/js/components/SettingsModal.js
  source/js/scripts/app.js
Labels: enhancement

#199 Remove timer hover behavior when running
  source/js/components/TimerUI.js
  source/scss/app.scss
Labels: cleanup, UI

#198 Update instruction card images and content
  source/assets/images/create-task-list-mobile.webp
  source/assets/images/create-task-list.webp
  source/assets/images/stats-modal-mobile.webp
  source/assets/images/stats-modal.webp
  source/assets/images/viewable-task-list-mobile.webp
  source/assets/images/viewable-task-list.webp
  source/js/components/InfoModal.js
Labels: enhancement

#200 Cleanup/pwa lighthouse checks
  source/app.html
  source/assets/icons/icon144.png
  source/assets/icons/icon144.webp
  source/assets/icons/icon180.png
  source/assets/icons/icon180.webp
  source/assets/icons/icon196.png
  source/assets/icons/icon196.webp
  source/assets/icons/icon270.png
  source/assets/icons/icon270.webp
  source/assets/icons/icon512.png
  source/assets/icons/icon512.webp
  source/index.html
  source/manifest.json
Labels: cleanup

#203 Fix enter on mobile bug
  source/__tests__/EditableTaskList.test.js
  source/js/components/EditableTaskListInput.js
Labels: bug, UI

#204 Fix task list view on tablet
  source/app.html
Labels: enhancement, UI

#208 Enhancement/demo commit
  source/js/components/MenuIcons.js
Labels: enhancement, UI

#211 Update index.html
  source/index.html
Labels: enhancement, UI

#205 update event diagram
  specs/interface/wireframe/eventdiagram-r1.drawio.png
Labels: documentation

#210 Updated systemDiagram
  specs/interface/wireframe/systemdiagram-r1.drawio.png
Labels: documentation

#214 fix errors
  README.md
  specs/onboard.md
Labels: documentation, cleanup

#215 last few link errors
  specs/adrs/051022-frontend-decisions.md
  specs/adrs/052822-sprint3-adr.md
Labels: documentation, cleanup

#216 Clean up package.json and update to version 1.0.0
  package-lock.json
  package.json
Labels: cleanup
