Repository cse112-sp22-group4/Electric-Pomato, pull requests merged in 2022-05, with the labels that each got.

#44 Add parcel for code minification
  .gitignore
  .htmlnanorc
  .parcelrc.json
  babel.config.cjs
  babel.config.json
  package-lock.json
  package.json
  source/app.html
  source/done.html
  source/index.html
  source/js/scripts/app.js
  source/scss/main.scss
Labels: enhancement

#31 Chris backend cleanup
  source/__tests__/UsernameInput.test.js
  source/js/components/StartContainer.js
  source/js/components/UsernameInput.js
  source/js/components/WelcomeMessage.js
Labels: cleanup

#45 Github Action - Deploy Updates
  .github/workflows/deploy.yml
Labels: bug, enhancement

#46 Add git config to deploy step
  .github/workflows/deploy.yml
Labels: bug, enhancement

#48 Enhancement/GitHub action deploy
  .github/workflows/deploy.yml
Labels: bug, enhancement

#49 Add new steps for CI/CD pipeline
  .firebaserc
  .github/workflows/staging.yml
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/sample-test.js
  cypress/plugins/index.cjs
  cypress/support/commands.js
  cypress/support/index.js
  firebase.json
  package-lock.json
  package.json
Labels: enhancement, devops

#51 fix firebase preview url output
  .github/workflows/staging.yml
Labels: bug, enhancement, devops

#54 Fix firebase preview url output attempt 2
  .github/workflows/staging.yml
Labels: bug, enhancement, devops

#56 change deploy workflow to only work on source
  .github/workflows/deploy.yml
  cypress/integration/sample-test.js
Labels: bug, devops

#36 Changed localStorage calls
  source/js/components/LogsButton.js
  source/js/components/StartButtons.js
  source/js/scripts/done.js
Labels: cleanup

#59 Add JSDocs to deployment
  .github/workflows/deploy.yml
  package-lock.json
  package.json
Labels: bug, devops

#74 Add codacy code quality check github action
  .github/workflows/lint.yml
  admin/ci_cd/TBDs/phase1.drawio.png
  admin/ci_cd/TBDs/phase1.md
Labels: devops

#76 Enhancement/menu icons
  source/app.html
  source/index.html
  source/js/components/LogsButton.js
  source/js/components/MenuIcons.js
  source/js/scripts/app.js
  source/scss/main.scss
Labels: enhancement

#86 Limit codacy scan to only our js and scss files
  .github/workflows/lint.yml
Labels: devops

#91 Add ADRs for staging and code quality
  specs/adrs/050222-staging-workflow.md
  specs/adrs/050322-frontend-decisions.md
  specs/adrs/050722-code-quality-workflow.md
  specs/adrs/previous_110_decisions/021421-jest-workflow.md
  specs/adrs/previous_110_decisions/022021-deployment-workflow.md
  specs/adrs/previous_110_decisions/022021-jsdoc-workflow.md
Labels: documentation, devops

#89 Fix issue with new task item content being reset when editing a previous set task.
  source/js/components/EditableTaskListBody.js
Labels: bug

#93 fix workflow errors
  .github/workflows/lint.yml
Labels: devops

#96 Fix workflow errors
  .github/workflows/lint.yml
Labels: devops

#95 Add the stats report modal
  package-lock.json
  package.json
  source/__tests__/StatsModal.test.js
  source/app.html
  source/index.html
  source/js/components/InfoModal.js
  source/js/components/MenuIcons.js
  source/js/components/SettingsModal.js
  source/js/components/StatsModal.js
  source/js/scripts/app.js
  source/scss/main.scss
Labels: enhancement, UI

#99 Remove old home links
  source/app.html
  source/index.html
Labels: enhancement, UI

#102 Test/modal unit tests
  source/__tests__/InfoModal.test.js
  source/__tests__/SettingsModal.test.js
  source/js/backend.js
  source/js/components/SettingsModal.js
  source/js/constants/timerConstants.js
  source/js/scripts/app.js
Labels: testing

#110 Staging workflow fixes
  .github/workflows/jest.yml
  .github/workflows/lint.yml
  .github/workflows/staging.yml
Labels: bug, devops

#108 Enhancement/current task title
  source/app.html
  source/js/components/TimerUI.js
  source/js/scripts/app.js
  source/scss/main.scss
Labels: enhancement, UI

#113 Added fontawesome directories
  source/app.html
  source/done.html
  source/fontawesome/css/all.min.css
  source/fontawesome/webfonts/fa-brands-400.eot
  source/fontawesome/webfonts/fa-brands-400.svg
  source/fontawesome/webfonts/fa-brands-400.ttf
  source/fontawesome/webfonts/fa-brands-400.woff
  source/fontawesome/webfonts/fa-brands-400.woff2
  source/fontawesome/webfonts/fa-regular-400.eot
  source/fontawesome/webfonts/fa-regular-400.svg
  source/fontawesome/webfonts/fa-regular-400.ttf
  source/fontawesome/webfonts/fa-regular-400.woff
  source/fontawesome/webfonts/fa-regular-400.woff2
  source/fontawesome/webfonts/fa-solid-900.eot
  source/fontawesome/webfonts/fa-solid-900.svg
  source/fontawesome/webfonts/fa-solid-900.ttf
  source/fontawesome/webfonts/fa-solid-900.woff
  source/fontawesome/webfonts/fa-solid-900.woff2
  source/index.html
Labels: enhancement

#100 Update end session button behavior
  source/js/components/StatsModal.js
  source/js/scripts/app.js
Labels: enhancement

#114 add finish task button
  source/__tests__/BreakPrompt.test.js
  source/__tests__/FinishTaskButton.test.js
  source/js/components/BreakPrompt.js
  source/js/components/FinishTaskButton.js
  source/js/scripts/app.js
Labels: enhancement

#115 test commit
  source/js/components/MenuIcons.js
Labels: enhancement

#126 Update edit name button styling
  source/js/components/WelcomeMessage.js
Labels: enhancement, small, UI

#131 remove done.html/done.js
  package.json
  source/done.html
  source/js/scripts/done.js
Labels: cleanup, UI

#132 Revise finish task button popup text
  source/js/components/FinishTaskButton.js
Labels: enhancement, UI

#129 Fix view-only task list styling
  source/__tests__/ViewOnlyTaskList.test.js
  source/app.html
  source/js/components/ViewOnlyTaskListSection.js
  source/scss/main.scss
Labels: enhancement, small

#124 Bug / pomo timer throttle
  source/__tests__/Timer.test.js
  source/__tests__/TimerUI.test.js
  source/js/classes/Timer.js
Labels: bug

#136 Change behavior on resuming session
  source/__tests__/StartButtons.test.js
  source/js/backend.js
  source/js/components/StartButtons.js
  source/js/scripts/app.js
Labels: bug, UI

#141 Disable service worker registration in development mode
  source/js/scripts/registerSw.js
Labels: enhancement

#140 Add color themes functionality
  source/app.html
  source/index.html
  source/js/components/SettingsModal.js
  source/js/constants/userThemes.js
  source/js/scripts/loadUserTheme.js
  source/scss/app.scss
  source/scss/components.scss
  source/scss/index.scss
  source/scss/main.scss
  source/scss/themes.scss
  source/scss/variables.scss
Labels: enhancement, UI

#163 Fix issue with service worker failing to install
  source/serviceWorker.js
Labels: bug

#154 Add new library for stats modal, change stats modal behavior
  .eslintrc.cjs
  package-lock.json
  package.json
  source/__tests__/StatsModal.test.js
  source/dependencies/zingchart-es6.min.js
  source/js/components/StatsModal.js
  source/js/constants/lineColors.js
  source/js/constants/lineConfig.js
  source/js/scripts/app.js
  source/scss/components.scss
  source/scss/main.scss
  source/scss/themes.scss
  specs/adrs/052522-charting-library.md
Labels: enhancement, UI

#164 Enhancement/audio notifications
  source/audio/notification-ping.mp3
  source/js/scripts/app.js
Labels: enhancement

#156 Enhancement/expected pomo
  cypress.json
  cypress/integration/TaskTime.js
  source/app.html
  source/js/classes/TaskList.js
  source/js/components/ViewOnlyTaskList.js
  source/js/scripts/app.js
Labels: enhancement

#168 Update website title/favicon according to timer
  source/img/favicon.ico
  source/img/icons/icon144.png
  source/img/icons/icon180.png
  source/img/icons/icon196.png
  source/img/icons/icon270.png
  source/img/icons/icon512.png
  source/img/logo.png
  source/img/logo.svg
  source/js/components/TimerUI.js
  source/js/scripts/app.js
Labels: enhancement, UI
